### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by snowsky** [zhuangbiaowei/docker-console#2]
Everything fine after running bundle install, but failed to run exec command:

root@ubuntu-14:/vagrant/docker-console# bundle exec ./bin/docker-console
ls: cannot access /home/vagrant/.docker/machine/machines: No such file or directory

**Comment by snowsky** [comment]
just found the directory "~/.docker/machine/machines" should be existing before running the command.

**Comment by zhuangbiaowei** [comment]
please run this command:
$ docker-machine -D ls
then give me the result, thx!
